"""ItemVenda

Revision ID: 407dea46b33f
Revises: 0cb2470bbd48
Create Date: 2021-03-08 12:05:53.553716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407dea46b33f'
down_revision = '0cb2470bbd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_por_item', sa.Float(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_venda')
    # ### end Alembic commands ###
